# Generated by Django 4.2.7 on 2023-12-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
